language: python
cache: pip

python:
  - "3.7"

env:
  - DJANGO="django>=1.11,<1.12"
  - DJANGO="django>=2.0,<2.1"
  - DJANGO="django>=2.1,<2.2"
  - DJANGO="django>=2.2,<3.0"
  - DJANGO="django>=3.0,<3.1"

branches:
  only:
    - master

before_install:
  - pip install -U pip wheel setuptools
  - pip install --no-cache-dir -U -r requirements-test.txt

install:
  - pip install $DJANGO
  - pip install -e .[qa]

before_script:
  - openwisp-utils-qa-checks --migration-path "./tests/test_project/migrations"

script:
  - coverage run --source=openwisp_utils runtests.py

after_success:
  coveralls
